siteTitle = 'Món Ngon Điểm Tâm'
siteDescr = 'Địa điểm ăn uống Bình Dương'
siteDescription = "Hãy ăn uống ngay."
siteUrl = "https://thegioidaudua.vn"
siteBandcampUrl = 'https://thegioidaudua.vn'
siteSoundcloudUrl = 'https://soundcloud.com/sentimony'
siteFacebookUrl = 'https://www.facebook.com/bepnhaty/'
siteDiscogsUrl = 'https://www.discogs.com/label/82598-Sentimony-Records'
siteTwitterUrl = 'https://twitter.com/nihon_ne'
siteGoogleplusUrl = ''
siteGithubUrl = 'https://github.com/nihonne'
siteYoutubeUrl = 'https://www.youtube.com/cumoi'

linkPrefix = '/'
